name: login_with_amazon_example
description: Demonstrates how to use the login_with_amazon plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  instrumentation_adapter: ^0.1.3

  login_with_amazon:
    path: ../

flutter:
  uses-material-design: true