name: login_with_amazon
description: Implements the LoginWithAmazon SDK as a Flutter plugin.
version: 0.0.5
author: sebastian.roth@gmail.com
homepage: https://github.com/ened/login_with_amazon

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  crypto: ^2.1.3
  meta: ^1.1.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.ened.login_with_amazon
    pluginClass: LoginWithAmazonPlugin
